# rules.mk - Common build rules for ai-glib
#
# Copyright (C) 2025
# SPDX-License-Identifier: AGPL-3.0-or-later

# Object subdirectories (derived from source list)
OBJ_DIRS := $(sort $(dir $(LIB_OBJECTS)))

# Header dependencies, generated by the compiler.
#
# There were none.  Nothing in this build knew that ai-claude-client.o
# includes ai-response.h, so editing *any* header left every object that
# included it stale -- `make` reported nothing to do and relinked a
# library built from the old declarations.  That is the worst kind of
# stale, because it is silent and it survives a test run: a change to a
# private header could be verified against a binary that did not contain
# it, which is exactly how a sabotage check comes back green.
#
# -MMD writes the list as a side effect of the compile that already
# happened, so it costs nothing; -MP adds a phony target per header so a
# deleted or renamed one is not "No rule to make target".  System headers
# are excluded (-MMD rather than -MD): glib moves under us on an image
# update and rebuilding the world for that is not what this is for.
#
# The link-and-compile rules below get -MF explicitly, because their
# output has no .o suffix for the compiler to substitute.
DEPFLAGS = -MMD -MP

LIB_DEPS     := $(LIB_OBJECTS:.o=.d)
TEST_DEPS    := $(addsuffix .d,$(TEST_BINARIES))
EXAMPLE_DEPS := $(addsuffix .d,$(EXAMPLE_BINARIES))
BIN_DEPS     := $(addsuffix .d,$(BIN_BINARIES))

# Compiler and linker options are command-line inputs, not source-file
# timestamps. Without a recorded signature, switching from ASAN=1 to a plain
# build can leave instrumented objects and a shared library in place; the next
# unsanitized test then fails to link on unresolved __asan_* symbols.
#
# FORCE runs the comparison on every invocation, but the stamp's timestamp
# changes only when the effective flags do. Objects therefore rebuild exactly
# when the build configuration changes, while repeated identical builds remain
# incremental.
.PHONY: FORCE
FORCE:

$(BUILD_FLAGS_STAMP): FORCE | $(OUTDIR)
	@{ \
		printf '%s\n' "CC=$(CC)" \
			"CFLAGS=$(BUILD_CONFIG_CFLAGS)" \
			"LDFLAGS=$(BUILD_CONFIG_LDFLAGS)" \
			> $@.tmp; \
		if test -r $@ && cmp -s $@.tmp $@; then \
			rm -f $@.tmp; \
		else \
			mv -f $@.tmp $@; \
		fi; \
	}

# Generic pattern rule for object files.
# Order-only deps on $(OUTDIR)/config.h and $(OUTDIR)/ai-version.h prevent a
# parallel-build race; the per-objects regular prereq in Makefile triggers
# recompilation when either header changes.
$(OBJDIR)/%.o: $(SRCDIR)/%.c $(BUILD_FLAGS_STAMP) | $(OBJ_DIRS) $(OUTDIR)/config.h $(OUTDIR)/ai-version.h
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(DEPFLAGS) -c $< -o $@

# Create build directories
$(OUTDIR):
	mkdir -p $(OUTDIR)

$(OBJDIR): | $(OUTDIR)
	mkdir -p $(OBJDIR)

$(OBJ_DIRS): | $(OBJDIR)
	mkdir -p $@

# Test compilation rule
# $(TEST_HEADERS) is a prerequisite of every test so that editing the shared
# loopback-server harness rebuilds the tests that include it.  Without it a
# change to test-server.h silently leaves stale binaries behind.
#
# $ORIGIN, not $(OUTDIR).
#
# $(OUTDIR) is a *relative* path -- build/debug -- so a runpath built
# from it resolves against whatever directory the binary is run from.
# Run a test from its own project it finds the library beside it; run it
# from anywhere else and the loader falls through to the installed
# libai-glib, so the binary tests whatever is on the machine rather than
# what was just compiled.  Silently: the library has the same soname,
# the tests run, and only an assertion about something recently changed
# tells you the answer came from the wrong place.
#
# $ORIGIN is expanded by the loader to the directory of the binary
# itself, so build/debug/tests/foo finds build/debug/ wherever it is
# started from and wherever the tree is moved to.  Single-quoted so make
# and the shell both pass it through to the linker unexpanded.
#
$(OUTDIR)/tests/%: $(TESTDIR)/%.c $(TEST_HEADERS) $(LIB_SHARED) | $(OUTDIR)/tests
	$(CC) $(CFLAGS) $(DEPFLAGS) -MF $@.d -I$(SRCDIR) $< -o $@ -L$(OUTDIR) -l$(PROJECT_NAME)-1.0 $(LDFLAGS) -Wl,-rpath,'$$ORIGIN/..'

$(OUTDIR)/tests: | $(OUTDIR)
	mkdir -p $@

# Example compilation rule
# $ORIGIN for the same reason as the test rule above.
$(OUTDIR)/examples/%: $(EXAMPLEDIR)/%.c $(LIB_SHARED) | $(OUTDIR)/examples
	$(CC) $(CFLAGS) $(DEPFLAGS) -MF $@.d -I$(SRCDIR) $< -o $@ -L$(OUTDIR) -l$(PROJECT_NAME)-1.0 $(LDFLAGS) -Wl,-rpath,'$$ORIGIN/..'

$(OUTDIR)/examples: | $(OUTDIR)
	mkdir -p $@

# CLI binary compilation rule (the `ai` front-end).
# ai-glib is linked STATICALLY ($(LIB_STATIC)) so the installed binary has
# no runtime dependency on the ai-glib shared library; the system libraries
# (glib/gobject/gio/libsoup/json-glib/libxml2) and the bundled yaml-glib
# static archive (via $(LDFLAGS)) are pulled in as usual.
$(OUTDIR)/bin/%: $(BINDIR)/%.c $(LIB_STATIC) | $(OUTDIR)/bin
	$(CC) $(CFLAGS) $(DEPFLAGS) -MF $@.d -I$(SRCDIR) $< -o $@ $(LIB_STATIC) $(LDFLAGS)

$(OUTDIR)/bin: | $(OUTDIR)
	mkdir -p $@

# The generated dependency lists.  Included last and with a leading dash:
# they do not exist on a clean tree, and make re-reads the makefile once
# the first build has produced them.
-include $(LIB_DEPS) $(TEST_DEPS) $(EXAMPLE_DEPS) $(BIN_DEPS)

# Clean current build type and the bundled yaml-glib build
.PHONY: clean
clean:
	rm -rf $(OUTDIR)
	rm -f $(PROJECT_NAME)-1.0.pc
	$(MAKE) -C $(YAML_GLIB_DIR) clean DEBUG=0 ASAN=0 UBSAN=0 2>/dev/null || true

# Clean everything (both build types + deps)
.PHONY: clean-all
clean-all:
	rm -rf $(BUILDDIR)
	rm -f $(PROJECT_NAME)-1.0.pc
	$(MAKE) -C $(YAML_GLIB_DIR) clean-all DEBUG=0 ASAN=0 UBSAN=0 2>/dev/null || true

# Distclean is an alias for clean-all
.PHONY: distclean
distclean: clean-all

# Help
.PHONY: help
help:
	@echo "ai-glib build system"
	@echo ""
	@echo "Targets:"
	@echo "  all          - Build shared and static libraries (default)"
	@echo "  shared       - Build shared library only"
	@echo "  static       - Build static library only"
	@echo "  test         - Build and run tests"
	@echo "  test-verbose - Build and run tests with verbose output"
	@echo "  test-gi      - Run the PyGObject binding smoke test (needs python3-gobject)"
	@echo "  test-gir-clean - Assert g-ir-scanner emits zero warnings"
	@echo "  examples     - Build example programs"
	@echo "  binaries     - Build installable CLI binaries (the 'ai' front-end)"
	@echo "  gir          - Generate GObject introspection data (requires GIR=1)"
	@echo "  install      - Install library and headers"
	@echo "  uninstall    - Uninstall library and headers"
	@echo "  clean        - Remove current build type ($(BUILD_TYPE)) and dep builds"
	@echo "  clean-all    - Remove all build artifacts and dep builds"
	@echo "  distclean    - Same as clean-all"
	@echo "  help         - Show this help"
	@echo ""
	@echo "Build options:"
	@echo "  DEBUG=1      - Build with debug symbols and no optimization"
	@echo "  GIR=1        - Build GObject introspection (.gir/.typelib)"
	@echo "  ASAN=1       - Enable address sanitizer"
	@echo "  UBSAN=1      - Enable undefined behavior sanitizer"
	@echo "  PREFIX=/path - Set installation prefix (default: /usr/local)"
	@echo ""
	@echo "Output directories:"
	@echo "  make         -> build/release/"
	@echo "  make DEBUG=1 -> build/debug/"
