#!/bin/sh
#
# gen-build-stamp.sh - write the build provenance header
#
# Copyright (C) 2026
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Usage: gen-build-stamp.sh OUT SRCDIR VERSION PREFIX LIBDIR INCLUDEDIR TYPE
#
# Run on every make invocation (the rule has FORCE), so it must only
# touch OUT when something in it changed: the header is included by one
# object, and rewriting it each time would relink the library and every
# binary on every `make`.  The build date is the one field that always
# differs, so it is left out of the comparison and only moves when
# something else did.
#
# Two things are load-bearing:
#
#  - git runs with --no-optional-locks and safe.directory for the tree.
#    `sudo make install` runs this as root in a tree root does not own:
#    without safe.directory git refuses, and a refusal would rewrite the
#    header as "not a git checkout" and install a binary that can no
#    longer update itself.  Without --no-optional-locks the status
#    refresh would leave a root-owned index behind in the user's tree.
#
#  - When git fails and OUT already exists, OUT is left alone for the
#    same reason: an old answer beats an invented one.

set -u

out=$1
srcdir=$2
version=$3
prefix=$4
libdir=$5
includedir=$6
buildtype=$7

gitc() {
	git -C "$srcdir" --no-optional-locks -c "safe.directory=$srcdir" "$@" 2>/dev/null
}

cstr() {
	printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

commit=
describe=
dirty=0
# The tree must be the top of its own repository.  ai-glib vendored as a
# plain directory inside some other project would otherwise stamp that
# project's commit, and the updater would go on to pull it.
real=$(cd "$srcdir" 2>/dev/null && pwd -P) || real=
if top=$(gitc rev-parse --show-toplevel) && [ "$top" = "$real" ] &&
   commit=$(gitc rev-parse --verify -q HEAD); then
	describe=$(gitc describe --tags --always --abbrev=12 HEAD) || describe=$commit
	if [ -n "$(gitc status --porcelain --untracked-files=no --ignore-submodules=all)" ]; then
		dirty=1
	fi
	srcdir=$top
else
	commit=
	describe=
	if [ -f "$out" ]; then
		exit 0
	fi
fi

body=$(cat <<EOT
/* Generated by build-aux/gen-build-stamp.sh. Do not edit. */
#pragma once
#define AI_BUILD_STAMP_VERSION "$(cstr "$version")"
#define AI_BUILD_STAMP_COMMIT "$(cstr "$commit")"
#define AI_BUILD_STAMP_DESCRIBE "$(cstr "$describe")"
#define AI_BUILD_STAMP_DIRTY $dirty
#define AI_BUILD_STAMP_SOURCE_DIR "$(cstr "$srcdir")"
#define AI_BUILD_STAMP_PREFIX "$(cstr "$prefix")"
#define AI_BUILD_STAMP_LIBDIR "$(cstr "$libdir")"
#define AI_BUILD_STAMP_INCLUDEDIR "$(cstr "$includedir")"
#define AI_BUILD_STAMP_TYPE "$(cstr "$buildtype")"
EOT
)

if [ -f "$out" ] && [ "$(grep -v '^#define AI_BUILD_STAMP_DATE ' "$out")" = "$body" ]; then
	exit 0
fi

if [ -n "${SOURCE_DATE_EPOCH:-}" ]; then
	date=$(date -u -d "@$SOURCE_DATE_EPOCH" +%Y-%m-%dT%H:%M:%SZ 2>/dev/null) || date=
else
	date=$(date -u +%Y-%m-%dT%H:%M:%SZ)
fi

printf '%s\n#define AI_BUILD_STAMP_DATE "%s"\n' "$body" "$date" > "$out.tmp" && mv -f "$out.tmp" "$out"
