/*
 * ai-error.c - Error domain and codes for ai-glib
 *
 * Copyright (C) 2025
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This file is part of ai-glib.
 */

#include "config.h"

#include "core/ai-error.h"

/**
 * ai_error_quark:
 *
 * Gets the ai-glib error quark.
 *
 * The error quark is used to identify errors from the ai-glib library.
 * All errors generated by ai-glib will use this quark as their domain.
 *
 * Returns: the error quark for ai-glib
 */
GQuark
ai_error_quark(void)
{
    return g_quark_from_static_string("ai-glib-error-quark");
}

/**
 * ai_error_get_type:
 *
 * Gets the #GType for #AiError.
 *
 * This function registers the #AiError enumeration with the GLib type system
 * on first call.
 *
 * Returns: the #GType for #AiError
 */
GType
ai_error_get_type(void)
{
    static GType error_type = 0;

    if (g_once_init_enter(&error_type))
    {
        static const GEnumValue values[] = {
            { AI_ERROR_INVALID_API_KEY, "AI_ERROR_INVALID_API_KEY", "invalid-api-key" },
            { AI_ERROR_RATE_LIMITED, "AI_ERROR_RATE_LIMITED", "rate-limited" },
            { AI_ERROR_NETWORK_ERROR, "AI_ERROR_NETWORK_ERROR", "network-error" },
            { AI_ERROR_TIMEOUT, "AI_ERROR_TIMEOUT", "timeout" },
            { AI_ERROR_INVALID_REQUEST, "AI_ERROR_INVALID_REQUEST", "invalid-request" },
            { AI_ERROR_INVALID_RESPONSE, "AI_ERROR_INVALID_RESPONSE", "invalid-response" },
            { AI_ERROR_MODEL_NOT_FOUND, "AI_ERROR_MODEL_NOT_FOUND", "model-not-found" },
            { AI_ERROR_CONTEXT_LENGTH_EXCEEDED, "AI_ERROR_CONTEXT_LENGTH_EXCEEDED", "context-length-exceeded" },
            { AI_ERROR_CONTENT_FILTERED, "AI_ERROR_CONTENT_FILTERED", "content-filtered" },
            { AI_ERROR_SERVER_ERROR, "AI_ERROR_SERVER_ERROR", "server-error" },
            { AI_ERROR_SERVICE_UNAVAILABLE, "AI_ERROR_SERVICE_UNAVAILABLE", "service-unavailable" },
            { AI_ERROR_PERMISSION_DENIED, "AI_ERROR_PERMISSION_DENIED", "permission-denied" },
            { AI_ERROR_INSUFFICIENT_QUOTA, "AI_ERROR_INSUFFICIENT_QUOTA", "insufficient-quota" },
            { AI_ERROR_CANCELLED, "AI_ERROR_CANCELLED", "cancelled" },
            { AI_ERROR_NOT_SUPPORTED, "AI_ERROR_NOT_SUPPORTED", "not-supported" },
            { AI_ERROR_CONFIGURATION_ERROR, "AI_ERROR_CONFIGURATION_ERROR", "configuration-error" },
            { AI_ERROR_SERIALIZATION_ERROR, "AI_ERROR_SERIALIZATION_ERROR", "serialization-error" },
            { AI_ERROR_STREAMING_ERROR, "AI_ERROR_STREAMING_ERROR", "streaming-error" },
            { AI_ERROR_TOOL_ERROR, "AI_ERROR_TOOL_ERROR", "tool-error" },
            { AI_ERROR_UNKNOWN, "AI_ERROR_UNKNOWN", "unknown" },
            { 0, NULL, NULL }
        };

        GType type = g_enum_register_static("AiError", values);
        g_once_init_leave(&error_type, type);
    }

    return error_type;
}
